export interface IStanding {
    leagueName:         string;
    teamName:           string;
    teamLogo:           string;
    rank:               number;
    points:             number;
    goalsDiff:          number;
    form:               string;
    description:        string;
    played:             number;
    win:                number;
    draw:               number;
    lose:               number;
    goalsFor:           number;
    goalsAgainst:       number;
    homePlayed:         number;
    homeWin:            number;
    homeDraw:           number;
    homeLose:           number;
    homeGoalsFor:       number;
    homeGoalsAgainst:   number;
    awayPlayed:         number;
    awayWin:            number;
    awayDraw:           number;
    awayLose:           number;
    awayGoalsFor:       number;
    awayGoalsAgainst:   number;
    updated:            string;
}